import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Syne, DM_Sans } from "next/font/google";
import Footer from "@/components/Footer";

const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });
const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syne} ${dmSans} h-full antialiased`}>
      <Navbar></Navbar>
      <body className="min-h-full flex flex-col">{children}</body>
      <Footer></Footer>
    </html>
  );
}
